### ISSUE TITLE
Se agrega arriba de todo, no hay que recorrer hasta el final.

### ISSUE THREAD

**Issue by josemariasola** [solasantiago/TrabajosDelCurso#4]
https://github.com/solasantiago/TrabajosDelCurso/blob/6b50c892dabd0d066ae87c8a1dc9694b1883cb3a/Stack/Enlazada/Stack.h#L12-L13

**Comment by solasantiago-zz** [comment]
Profe, no estaría entendiendo el error.
¿A que se refiere con agregar arriba de todo? ¿Al puntero o a las lineas de código?

**Comment by josemariasola** [comment]
En tu implementación cada vez que pusheas vas hasta el final, cuando en realidad, debes inserta el inicio, es como que tu pila está al revés. Funcionalmente se ve bien, pero cada insersión y remoción demandan recorrer toda la lista, cuando la remoción y la inserción se hacen en el extremo al que apunta FirstNode. 

Stack vacío: p--->\
Push(13): p--->[13]--->\
Push(45): p--->[45]--->[13]--->\
Push(26): p--->[26]--->[45]--->[13]--->\
Pop(): p--->[45]--->[13]--->\
Pop(): p--->[13]--->\
Pop(): p—>\
//

**Comment by solasantiago-zz** [comment]
Listo profe. Noto que me la había complicado demasiado.

Resuelto!
