### ISSUE TITLE
La queue enlazada se implementa con dos punteros, uno el inicio de la la cola, y otro al final de la cola.

### ISSUE THREAD

**Issue by josemariasola** [solasantiago/TrabajosDelCurso#6]
https://github.com/solasantiago/TrabajosDelCurso/blob/0f17dd63ffe8c8a1a9c0028f73a322f8b9020a81/Queue/Enlazada/Queue.h#L12

struct Queue {
  Node* inicio= nullptr; //recomiendo cambiar el nombre a este puntero para que sea más claro.
  Node* final= nullptr; // agergar este puntero
};

**Comment by solasantiago-zz** [comment]
Corregido!!
