### ISSUE TITLE
Usar módulo n para queue contigua

### ISSUE THREAD

**Issue by josemariasola** [solasantiago/TrabajosDelCurso#7]
https://github.com/solasantiago/TrabajosDelCurso/blob/0f17dd63ffe8c8a1a9c0028f73a322f8b9020a81/Queue/Contigua/QueueContigua.cpp#L9-L48

En vez múltiples selecciones (ifs), usar aritmética módulo N.

Ayuda
https://stackoverflow.com/questions/26443294/queue-with-mod-operation
http://opendatastructures.org/ods-cpp/2_3_Array_Based_Queue.html

**Comment by solasantiago-zz** [comment]
Quisiera saber si le parece bien la corrección

Mi planteo fue que si se va a saber con los datos que se va a manejar la memoria estática (colocandole un valor a N), no hace falta plantear el aviso de error.

Pero puedo armarlo con dicho aviso, pero creo que lo que corregí es lo que usted estaba buscando con este issue.

Un saludo!

**Comment by josemariasola** [comment]
Aritmética módulo N no tiene que ver con el tratamiento de error, si no, como calcular índices.
Si tu arreglo es de N=5 elementos, el inicio está en i=2 y el fin en f=4, entonces, tenes lugar para seguir encolando?

```
+---+---+---+---+---+  
|   |   |x  |y  |z  |  
+---+---+---+---+---+  
  0   1   2   3   4
          i       f
```  

La respuesta es sí, tenes dos lugares libreas adelante; pero eso es antes del inicio.

Entonces, si haces `f+1` da `5` y no lo podes usar como subíndice, pero, si haces
`f = (f+1)%5 // % es el resto` haces el resto de 5/5 que es cero y que coincide con el índice buscado.

Eso es aritmética módulo N, en este cas N es 5. En el reloj de agujas N es 12, por eso si a 12 le sumamos uno da 1 y no 13.
